repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8

- repo: local
  hooks:
    - id: export-dev-requirements
      name: Export DEVELOPMENT requirements
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --with dev --output requirements/dev.txt
      files: ^(pyproject.toml|poetry.lock)$
    - id: export-prod-requirements
      name: Export PRODUCTION requirements
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --without dev --output requirements/prod.txt
      files: ^(pyproject.toml|poetry.lock)$
