version: '3.12'

services:

  db:
    env_file:
      - .env
    image: ${POSTGRES_IMAGE}
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      LANG: "ru_RU.UTF-8"
      POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=ru-RU'
      POSTGRES_IMAGE_VERSION:
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'" ]
      interval: 3s
      timeout: 3s
      retries: 5


  backend:
    build:
      context: ..
      dockerfile: /src/backend/Dockerfile
    container_name: backend
    command: >
      bash -c "python manage.py migrate &&
               python manage.py createsuperuser --noinput --username admin --email admin@ya.ru &&
               python manage.py collectstatic --clear --noinput &&
               gunicorn coliving_bot.wsgi:application --bind 0:9090"
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../.data/logs/:/app/.data/logs/
    env_file:
      - .env
    depends_on:
      - db
    image: coliving_bot_backend:latest

  bot:
    build:
      context: ..
      dockerfile: /src/bot/Dockerfile
    container_name: bot
    command: bash -c "python run_bot.py"
    env_file:
      - .env
    restart: always
    volumes:
      - ../.data/logs/:/app/.data/logs/
    depends_on:
      - backend
    image: coliving_bot_bot:latest

  nginx:
    env_file:
      - .env
    image: ${NGINX_IMAGE}
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - bot
      - backend


volumes:
  static:
  media:
  data: