version: '3.12'

services:
  db:
    image: ${POSTGRES_IMAGE}
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      LANG: "ru_RU.UTF-8"
      POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=ru-RU'
    expose:
      - "5432"
    env_file:
      - .env


  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --clear --noinput &&
               gunicorn coliving_bot.wsgi:application --bind 0:9090"
    restart: always
    volumes:
      - static:/app/backend/static/
      - media:/app/backend/media/
      - ../.data/logs/:/app/.data/logs/
    env_file:
      - .env
    depends_on:
      - db

  bot:
    image: ${BOT_IMAGE}
    container_name: bot
    command: bash -c "cd bot/ && python run_bot.py"
    env_file:
      - .env
    restart: always
    volumes:
      - ../.data/logs/:/app/.data/logs/
    depends_on:
      - backend

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    env_file:
      - .env
    ports:
      - "9090:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - bot


volumes:
  static:
  media:
  data: