REPORT_YES_BUTTON = "Да, я хочу пожаловаться"
REPORT_NO_BUTTON = "Нет, я ошибся"
SCREEN_YES_BUTTON = "Да, я хотел бы прикрепить скриншот"
SCREEN_NO_BUTTON = "Нет, у меня нет скриншота"
REPORT_CATEGORY = "Категории жалоб"
CANCEL_BUTTON = "Отмена"
SAVE_SCREENSHOT_BUTTON = "Сохранить скриншот 📁️"

CATEGORY_SPAM_BUTTON = "Спам"
CATEGORY_INCORRECT_DATA_BUTTON = "Не совпадают личные данные"
CATEGORY_CHEATER_BUTTON = "Мошенник"
CATEGORY_PROHIB_ACTIV_BUTTON = "Запрещенная деятельность"
CATEGORY_BAD_LANG_BUTTON = "Оскорбления, мат"
CATEGORY_OTHER_BUTTON = "Другое"
