REPORT_YES_BUTTON = "Да, я хочу пожаловаться"
REPORT_NO_BUTTON = "Нет, я ошибся"
SCREEN_YES_BUTTON = "Да, я хотел бы прикрепить скриншот"
SCREEN_NO_BUTTON = "Нет, у меня нет скриншота"
REPORT_CATEGORY = "Категории жалоб"
CANCEL_BUTTON = "Отмена"
