CANCEL_BUTTON = "Отмена"

LOCATION_PREFIX = "select_location"
LOCATION_CALLBACK_PATTERN = rf"^{LOCATION_PREFIX}:(.+)$"

ROOM_TYPE_PREFIX = "select_room_type"
ROOM_TYPE_CALLBACK_PATTERN = rf"^{ROOM_TYPE_PREFIX}:(.+)$"
