OK_SETTINGS_BTN = "Всё ок, начинаем поиск"
EDIT_SETTINGS_BTN = "Изменить настройки поиска"
MALE_BTN = "Парень"
FEMALE_BTN = "Девушка"
ANY_GENDER_BTN = "Неважно"
ANY_AGE_BTN = "Неважно"
LIKE_BTN = "👍"
DISLIKE_BTN = "👎"
WAIT_BTN = "Ждать"
YES_BTN = "Да"
NO_BTN = "Нет"

SEE_PROFILE = "Посмотреть анкету {profile_id}"
