# Generated by Django 5.0 on 2023-12-19 03:54

import images.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colivingimage",
            name="image",
            field=models.ImageField(
                upload_to="images/",
                validators=[images.validators.image_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="image",
            field=models.ImageField(
                upload_to="images/",
                validators=[images.validators.image_size_validator],
            ),
        ),
    ]
