# Generated by Django 5.0 on 2023-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_colivingimage_image_alter_profileimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colivingimage",
            name="file_id",
            field=models.TextField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="file_id",
            field=models.TextField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
