# Generated by Django 5.0 on 2023-12-19 15:54

import images.utils
import images.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_alter_colivingimage_file_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colivingimage",
            name="file_id",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="colivingimage",
            name="image",
            field=models.ImageField(
                upload_to=images.utils.images_directory_path,
                validators=[images.validators.image_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="file_id",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="image",
            field=models.ImageField(
                upload_to=images.utils.images_directory_path,
                validators=[images.validators.image_size_validator],
            ),
        ),
    ]
