# Generated by Django 5.0.6 on 2024-06-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                ("send_date", models.DateTimeField(verbose_name="Дата рассылки")),
            ],
        ),
    ]
