# Generated by Django 5.0.6 on 2024-06-07 02:49

import images.utils
import images.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=images.utils.images_directory_path,
                validators=[images.validators.image_size_validator],
                verbose_name="Фото для рассылки",
            ),
        ),
    ]
