# Generated by Django 5.0.6 on 2024-06-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_sended",
            field=models.BooleanField(default=False, verbose_name="Отправлено"),
        ),
    ]
