# Generated by Django 5.0.6 on 2024-06-17 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_remove_mailing_is_sended_mailing_is_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_sent",
        ),
        migrations.AddField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("is_waiting", "Ждёт"),
                    ("is_sending", "Отправляется"),
                    ("is_sent", "Отправлено"),
                ],
                default="is_waiting",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mailings/",
                verbose_name="Фото к сообщению",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="send_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Наличие рассылки проверяется каждый час, поэтому, если выставлено 12:34, рассылка начнётся в 13:00.",
                verbose_name="Дата рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="text",
            field=models.TextField(
                help_text='Здесь можно использовать некоторые теги HTML (<a href="https://core.telegram.org/bots/api#html-style">https://core.telegram.org/bots/api#html-style</a>). Например, <code>&lt;b&gt;жирный текст&lt;/b&gt;</code>. А также вставлять эмодзи 😊.',
                max_length=1024,
                verbose_name="Текст сообщения",
            ),
        ),
    ]
