# Generated by Django 5.0.4 on 2024-04-22 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Coliving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Отображать при поиске"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "room_type",
                    models.TextField(
                        choices=[
                            ("Комната", "Комната"),
                            ("Спальное место", "Спальное место"),
                        ],
                        verbose_name="Тип коливинга",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="profiles.location",
                        verbose_name="Местоположение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коливинг",
                "verbose_name_plural": "Коливинги",
                "ordering": ("room_type",),
                "abstract": False,
                "default_related_name": "%(class)s",
            },
        ),
        migrations.CreateModel(
            name="UserFromTelegram",
            fields=[
                (
                    "telegram_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Идентификатор пользователя Telegram",
                    ),
                ),
                (
                    "residence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roommates",
                        to="profiles.coliving",
                        verbose_name="Проживает в коливинге",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("telegram_id",),
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Отображать при поиске"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(30),
                            django.core.validators.RegexValidator(
                                message="Числа и спец. символы не поддерживаются",
                                regex="^[А-Яа-яA-Za-z\\s'-]+$",
                            ),
                        ],
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "sex",
                    models.TextField(
                        choices=[("Парень", "Парень"), ("Девушка", "Девушка")],
                        verbose_name="Пол",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Возраст",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="profiles.location",
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to="profiles.userfromtelegram",
                        verbose_name="Пользователь Telegram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "ordering": ("name", "sex", "location"),
                "abstract": False,
                "default_related_name": "%(class)s",
            },
        ),
        migrations.AddField(
            model_name="coliving",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colivings",
                to="profiles.userfromtelegram",
                verbose_name="Создатель коливинга",
            ),
        ),
    ]
