# Generated by Django 5.0 on 2023-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.TextField(
                choices=[("Парень", "Парень"), ("Девушка", "Девушка")],
                verbose_name="Пол",
            ),
        ),
    ]
