# Generated by Django 5.0 on 2023-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.TextField(verbose_name="Название"),
        ),
    ]
