# Generated by Django 5.0 on 2023-12-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coliving",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="coliving",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.location",
                verbose_name="Местоположение",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.location",
                verbose_name="Местоположение",
            ),
        ),
        migrations.AlterField(
            model_name="userfromtelegram",
            name="telegram_id",
            field=models.PositiveBigIntegerField(
                db_index=True,
                unique=True,
                verbose_name="Идентификатор пользователя Telegram",
            ),
        ),
    ]
