# Generated by Django 5.0 on 2023-12-25 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_coliving_about_alter_coliving_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(
                        message="Числа и спец. символы не поддерживаются",
                        regex="^[А-Яа-яA-Za-z\\s\\-]+$",
                    ),
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
