# Generated by Django 5.0.1 on 2024-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.TextField(unique=True, verbose_name="Название"),
        ),
    ]
