# Generated by Django 5.0.6 on 2024-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsefulMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Текст кнопки в меню "Полезное".',
                        max_length=32,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text=(
                            "Загрузите файл (например, PDF)."
                            " Это поле необязательно, если заполнена ссылка."
                        ),
                        null=True,
                        upload_to="materials/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text=(
                            "Введите URL-ссылку на материал."
                            " Это поле необязательно, если загружен файл."
                        ),
                        null=True,
                        verbose_name="Ссылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезный материал",
                "verbose_name_plural": "Полезные материалы",
            },
        ),
    ]
