# Generated by Django 5.0 on 2023-12-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_profile_name"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "category",
                    models.TextField(
                        choices=[
                            ("Категория 1", "Категория 1"),
                            ("Категория 2", "Категория 2"),
                            ("Категория 3", "Категория 3"),
                            ("Другое", "Другое"),
                        ],
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("Получено", "Получено"),
                            ("Просмотрено", "Просмотрено"),
                            ("Решено", "Решено"),
                            ("Отклонено", "Отклонено"),
                        ],
                        default="Получено",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_against",
                        to="profiles.userfromtelegram",
                        verbose_name="Обвиняемый",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filed_reports",
                        to="profiles.userfromtelegram",
                        verbose_name="Подавший жалобу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жалоба",
                "verbose_name_plural": "Жалобы",
                "ordering": ("-created_date",),
            },
        ),
    ]
