# Generated by Django 5.0 on 2023-12-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_profile_name"),
        ("search", "0002_userreport"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "reported_user"), name="Uniq report"
            ),
        ),
    ]
