# Generated by Django 5.0.6 on 2024-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_userreport_screenshot_alter_userreport_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreport",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
    ]
