MIN_AGE = 18
MAX_AGE = 99
MIN_NAME_LENGTH = 2
MAX_NAME_LENGTH = 30
MIN_ABOUT_LENGTH = 0
MAX_ABOUT_LENGTH = 500
PHOTO_MAX_NUMBER = 3

AGE_PATTERN = r"^(1[8-9]|[2-9]\d)$"

NAME_PATTERN = r"^[А-Яа-яA-Za-z\s'-]+$"
