MIN_AGE = 18
MAX_AGE = 99
MIN_NAME_LENGTH = 2
MAX_NAME_LENGTH = 30
MIN_ABOUT_LENGTH = 0
MAX_ABOUT_LENGTH = 1000
PHOTO_MAX_NUMBER = 3
NAME_PATTERN = "^[А-Яа-яA-Za-z'-]+$"
AGE_PATTERN = r"^(1[8-9]|[2-9]\d)$"

RECEIVED_PHOTOS_FIELD = "received_photos"
