MIN_AGE = 18
MAX_AGE = 99
MIN_NAME_LENGTH = 2
MAX_NAME_LENGTH = 30
MIN_ABOUT_LENGTH = 0
MAX_ABOUT_LENGTH = 1000
PHOTO_MAX_NUMBER = 3
NAME_PATTERN = "^[А-Яа-яA-Za-z'-]+$"
AGE_PATTERN = r"^(1[8-9]|[2-9]\d)$"

AGE_FIELD = "age"
SEX_FIELD = "sex"
NAME_FIELD = "name"
LOCATION_FIELD = "location"
ABOUT_FIELD = "about"
IMAGE_FIELD = "image"
IS_VISIBLE_FIELD = "is_visible"
RECEIVED_PHOTOS_FIELD = "received_photos"
